
osx_image: xcode10
language: swift
branches:
  only:
    - master

env:
  global:
    - WORKSPACE=Example/Giraffe.xcworkspace
    - SCHEME=Giraffe-Example SWIFT_VERSION=5.0
    - SDK=iphonesimulator12.0
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=12.0"

podfile: Example/Podfile

script:
  - swift -version
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
