
osx_image: xcode10.2
language: swift
branches:
  only:
    - master

env:
  global:
    - WORKSPACE=Example/Giraffe.xcworkspace
    - SCHEME=Giraffe-Example
    - SDK=iphonesimulator12.2
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone SE,OS=12.0"

podfile: Example/Podfile

script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty
